# fly.toml — sits alongside your Dockerfile in backend/
app = "mind-x-backend"
primary_region = "cdg"      # or whichever region you prefer

[build]
  # tell Fly to build using your Dockerfile
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[deploy]
  # auto_release = true   # you can enable this if you like